#!/bin/bash
#
# Author: louisadunne@gmail.com
# Sun Mar 10 16:50:24 GMT 2013
#
# A few commands for keeping track of cd history

# TODO
# 1. Add file support for persistence
# 2. Add named directories and a command to add a dir without moving to it (can
#    be used in the load file too.

alias   cd=cdh-cd
alias   cdh=cdh-history
alias   cdcl=cdh-clear

if [ "$CDHISTORY" == "" ]; then
    CDHISTORY=()
fi

cdh-cd()
{
    local dir index args

    args=()
    while [ $# -gt 0 ]; do
        case $1 in 
            -[a-Z]*)
                args+=($1)
                shift
                ;;
            *)
                dir="$*"
                break
        esac
    done

    if [ "$dir" == "" ]; then
        dir="$HOME"
    elif [[ $dir =~ ^[0-9]+ ]] || [[ $dir =~ ^-[0-9]+ ]]; then
        # positive or negative number supplied
        cdh-get-index $dir
        if [ $? -eq 0 ] && [ ! -d $1 ]; then
            \cd ${CDHISTORY[$index]}
            return 0
        fi
    fi

    \cd ${args[@]} "$dir" || return 1

    # Use $PWD from here...

    # No point saving home dir
    if [ "$PWD" == "$HOME" ]; then
        return 0
    fi

    # Don't add the dir if it's already in the list
    for ((index = 0; index < ${#CDHISTORY[@]}; index++)); do
        if [ "$PWD" == "${CDHISTORY[$index]}" ]; then
            return 0
        fi
    done

    # Save it
    index=${#CDHISTORY[@]}
    CDHISTORY[$index]=$PWD
    return 0
}

cdh-history()
{
    local index

    if [ "$CDHISTORY" == "" ]; then
        echo "<empty>"
        return 0
    else
        cdh-get-index $1 || return 1
    fi

    if [ $index == -1 ]; then
        for ((index = 0; index < ${#CDHISTORY[@]}; index++)); do
            echo "${index}: ${CDHISTORY[$index]} "
        done
        return
    else
        echo ${CDHISTORY[$index]}
    fi

    return 0
}

cdh-clear()
{
    local index tmp

    if [ "$CDHISTORY" == "" ]; then
        return 0
    fi

    cdh-get-index $1 || return 1
    if [ $index == -1 ]; then
        CDHISTORY=()
    else
        # unset leaves gaps so copy each element excluding $index
        tmp=()
        for ((i = 0; i < ${#CDHISTORY[@]}; i++)); do
            if [ $i -ne $index ]; then
                tmp+=(${CDHISTORY[$i]})
            fi
        done
        CDHISTORY=("${tmp[@]}")
    fi

    cdh-history
    return 0
}


cdh-get-index()
{
    if [ "$1" == "-" ]; then
        index=$(expr ${#CDHISTORY[@]} - 1)
    elif [[ $1 =~ ^[0-9]+ ]]; then
        index=$1
    elif [[ $1 =~ -[0-9]+ ]]; then
        index=$(expr ${#CDHISTORY[@]} - $(echo $1 | tr -d '-'))
    elif [ "$1" != "" ]; then
        echo "Unknown arg: $1"
        return 1
    else
        # do all
        index=-1
        return 0
    fi

    if [ $index -lt 0 -o $index -ge ${#CDHISTORY[@]} ]; then
        echo "$1 out of range"
        return 1
    fi

    return 0
}
